config/routes.rb
Rails.application.routes.draw do

  # Chat
  mount ActionCable.server => '/cable'
  resources :chatrooms
  resources :messages

  # Contacts
  resources :contacts, except: [:new, :create, :show]
  get "contacts/search", to: "contacts#search"

  # Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Events
  resources :events, except: [:index] do
    get 'attend', to: "events#attend"
    get 'addcontactbook', to: "events#addcontactbook"
  end

  get 'events', to: "events#search", as: 'search'
  
  # Attendances
  resources :attendances, only: [:destroy] do
    collection do
      get 'dashboard', to: "attendances#dashboard"
    end
  end
 
  # LinkedIn sign in/sign up
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  # Profile page
  resources :users, only: [:show]
  
  root to: 'pages#home'
  
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <%= link_to contacts_path do %>
    <i class="material-icons footer-icon">perm_contact_calendar</i>
  <% end %>

  <!-- If current user has any chats, direct to the last created, otherwise direct back to home page with flash message-->
  <% my_chats = current_user.chatroomusers %>
  <% unless my_chats.empty? %>
    <%= link_to chatroom_path(my_chats[-1].chatroom_id) do %>
      <i class="material-icons footer-icon">question_answer</i>
    <% end %>
  <% else %>
    <%= link_to events_path do %>
      <i class="material-icons footer-icon">question_answer</i>
    <% end %>
  <% end %>

  <%= link_to dashboard_attendances_path do %>
    <i class="material-icons footer-icon">assignment</i>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-wagon-left">
    <%= link_to search_path do %>
    <%= image_tag("Unify-logo.png", class:"logo-uni") %>
    <% end %>
    <a href="/events" class="logo">
      <h1>Unify</h1>
    </a>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">
    <div class="search-event-wrapper">
      <%#= link_to search_path do  %>
      <%#= image_tag("Icones/Search.png", class:"search-icon") %>
      <%# end %>
    </div>


    <!-- Different navigation if login or not -->
    <% unless user_signed_in? %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if user_signed_in? %>
          <% avatar_url = current_user.picture || "https://timeforgeography.co.uk/static/img/avatar-placeholder.png" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user.id) do  %>
                <%= image_tag("Icones/profile.png", class:"profile-icon") %> Profile
              <% end %>
            </li>
            <li>
              <%= link_to new_event_path do  %>
                <%= image_tag("Icones/bulb.png", class:"bulb-icon") %>Create event
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do  %>
               <%= image_tag("Icones/logout.png", class:"logout-icon") %>Log out
               <% end %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>