config/routes.rb
Rails.application.routes.draw do

  # Chat
  mount ActionCable.server => '/cable'
  resources :chatrooms
  resources :messages

  # Contacts
  resources :contacts, except: [:new, :create, :show]
  get "contacts/search", to: "contacts#search"

  # Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Events
  resources :events, except: [:index] do
    get 'attend', to: "events#attend"
    get 'addcontactbook', to: "events#addcontactbook"
  end

  get 'events', to: "events#search", as: 'search'
  
  # Attendances
  resources :attendances, only: [:destroy] do
    collection do
      get 'dashboard', to: "attendances#dashboard"
    end
  end
 
  # LinkedIn sign in/sign up
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  # Profile page
  resources :users, only: [:show]
  
  root to: 'pages#home'
  
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :location, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :category, presence: true

CATEGORIES = ['Tech', 'Human Resources', 'Education', 'Innovation', 'Food', 'Psychology', 'Design']
belongs_to :user
has_many :attendances, dependent: :destroy

mount_uploader :photo, PhotoUploader

 include PgSearch
  pg_search_scope :global_search, against: [ :title, :location, :start_time, :category],
  using: {tsearch: {prefix: true, any_word: true}}

  # [...]


def now?
  self.start_time <= Time.now and self.end_time >= Time.now
  #(- 10.minutes) doesn't work
end

def upcomming?
  self.start_time >= Time.now
end

def past?
  self.end_time <= Time.now
end



geocoded_by :location
after_validation :geocode, if: :location_changed?

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only:[:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create, :attend]

  # def index
  #   @events = Event.all
  #   end

  def show

    @alert_message = "You are viewing #{@event.title}"
    @event_coordinates = [@event]
    @hash = Gmaps4rails.build_markers(@event_coordinates) do |event, marker|
      if event.latitude
        marker.lat event.latitude
        marker.lng event.longitude
      else
        marker.lat '41.4089506'
        marker.lng '2.1523962'
        # CHANGE!
      end
    end
  end

  def new
    @event = Event.new
  end

  def create
    start_t = params[:event][:start_time]
    end_t = params[:event][:end_time]

    if start_t != "" && end_t != ""
      start_p =  DateTime.strptime(start_t, "%m/%d/%Y %H:%M %p")
      end_p = DateTime.strptime(end_t, "%m/%d/%Y %H:%M %p")
    end

    @event = Event.new(event_params)
    @event.start_time = start_p
    @event.end_time = end_p

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    @event.save
    redirect_to events_path
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  def attend

    @event = Event.find(params[:event_id])
    @user = current_user
    # @event_nearby = Event.near([@event.latitude, @event.longitude], 0.1).first

    # Check if user already has an attendance to the event clicked
    attended = current_user.attendances.select { |attendance| attendance.event_id == @event.id }

    if attended.empty?
      current_location_latitude = current_location["latitude"].to_f
      current_location_longitude = current_location["longitude"].to_f
      center_point = [current_location_latitude, current_location_longitude]
      box = Geocoder::Calculations.bounding_box(center_point, 10)
      #center_point_event = [@event.longitude, @event.latitude]
      if Event.within_bounding_box(box).map(&:id).include? @event.id
        Attendance.create(user_id: @user.id, event_id: @event.id)
        redirect_to event_path(@event)
        flash[:notice] = "You have successfully checked in to this event."
      else  redirect_to event_path(@event)
        flash[:alert] = "You can't check in as you are not at the event location."
      end
    else
      flash[:alert] = "You are already checked in to this event."
      redirect_to event_path(@event)
    end

  end

  def addcontactbook

    @event = Event.find(params[:event_id])
    @user_id = current_user.id
    @user_contact_id = params[:user_id].to_i
  if Contact.exists?(user_id: @user_id, user_contact_id: @user_contact_id)
      redirect_to event_path(@event)
      flash[:alert] = "You have already this user in your contactbook"

  else  Contact.create(user_id: @user_id, user_contact_id: @user_contact_id, event_id: @event.id)
        redirect_to event_path(@event)
        flash[:notice] = "You have successfully added a contact"
  end

end

 def search

    if params.has_key?(:search_value) and params[:search_value] != ""
      search = params[:search_value]
      @result = Event.global_search(search)

      @hash = Gmaps4rails.build_markers(@result) do |event, marker|
          marker.lat event.latitude
          marker.lng event.longitude
      end

    else
      @events =  Event.all
       @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      if event.latitude
        marker.lat event.latitude
        marker.lng event.longitude
      else
        marker.lat '41.4089506'
        marker.lng '2.1523962'
        # CHANGE!
      end
    end
  end
 render :index
end




      # if a parameter doesn't correspond to anything - add a note



  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :start_time, :end_time, :organization, :category, :location, :user_id, :photo, :photo_cache)
  end

  def require_login
    if !current_user
       flash[:alert] = "You need to sign in to do this action"
      redirect_to new_user_session_path
    end
  end
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
Events#destroy
Find me in app/views/events/destroy.html.erb

app/views/events/edit.html.erb
<div class="container" style="margin-bottom: 30px;">
  <h2 class="text-center">Create a new event</h2>
  <div class="row">
    <div class='col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3'>
      <%= simple_form_for @event do |f| %>  <!-- remote: true -->
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :title, required: true, autofocus: true %>
          <%= f.input :location, required: true, autofocus: true %>
          <%= f.input :description, required: true, autofocus: true %>
          <%= f.input :organization, required: false, autofocus: true %>
          <%= f.input :category, required: true, autofocus: true %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <p>*Be nice with the css, add an horizontal picture*</p>
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>


        <div class="form-actions">
          <%= f.button :submit, "Edit event", class: "navbar-wagon-item navbar-wagon-button btn"  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<!-- <div class="wrapper"> -->
  <div class="container-fluid home-page"> <!-- class home-page -->
    <div class="row">
<!-- Search bar -->
<div class="search events">
<%= form_tag('/events', method: 'get',  class:'navbar-wagon-search' ) do  %>
    <%= text_field_tag :search_value, params[:search_value], placeholder: 'Location, name, category...' , class: "navbar-wagon-search-input" %>
    <%= submit_tag 'search', class: 'btn btn-primary search-btn' %>
    <%end  %>
 </div>

<div class="wrapper-map">
          <div id="map" style="width: 100%; height: 320px;"></div>

          <% content_for(:after_js) do %>
            <%= javascript_tag do %>
              $(document).ready(function() {
                var handler = Gmaps.build('Google');
                handler.buildMap({ internal: { id: 'map' }, provider:{ scrollwheel: false } }, function() {
                  markers = handler.addMarkers(<%= raw @hash.to_json %>);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                  handler.getMap().setZoom(13);
                  if (markers.length == 0) {
                    handler.getMap().setZoom(2);
                  } else if (markers.length == 1) {
                    handler.getMap().setZoom(14);
                  }
                });
              });

            <% end %>
          <% end %>
  </div>

<div class="event-list-wrapper">
  <div class="container">
    <div class="row">
      <!-- <div class="col-xs-12"> -->

        <div class="event-list">
          <ul class="list-unstyled">

          <%if params[:search_value].nil? or params[:search_value] == ""  %>

            <%  @events.each do |event| %>
            <div class="col-xs-12 col-md-6">
              <li>

                <% if event.photo? %>
                  <% picture = event.photo %>
                <% else %>
                  <% picture = 'https://images.unsplash.com/photo-1478812954026-9c750f0e89fc?dpr=2&auto=format&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb&crop=&bg=' %>
                <% end %>

                <div class="event-li" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url(<%= cl_image_path picture %>); background-size: cover;">

                  <div class="event-category rounded-btn"><%= event.category %></div>
                  <h3><%= link_to event.title, event_path(event) %></h3>

                  <!-- <i class="fa fa-arrow-circle-right arrow" aria-hidden="true"></i> -->
                  <!-- <i class="fa fa-long-arrow-right arrow" aria-hidden="true"></i> -->
                  <!-- <img src='app/assets/images/background-image.jpg' class="arrow" /> -->

                  <p class="li-time"></p>
                  <p class="event-li-data">
                    <i class="fa fa-calendar" aria-hidden="true"></i>
                    <%= l(event.start_time, format: :long) %><br>
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <%= event.location %>
                  </p>
                </div>
              </li>
            </div>
            <% end %>



            <% elsif params[:search_value] != nil %>
            <%@result.each do |event| %>
            <div class="col-xs-12 col-md-6">
              <li>
                <div class="event-li">
                  <div class="event-category rounded-btn"><%= event.category %></div>
                  <h3><%= link_to event.title, event_path(event) %></h3>

                  <!-- <i class="fa fa-arrow-circle-right arrow" aria-hidden="true"></i> -->
                  <!-- <i class="fa fa-long-arrow-right arrow" aria-hidden="true"></i> -->
                  <!-- <img src='app/assets/images/background-image.jpg' class="arrow" /> -->
                  <p class="arrow"> &#x3e; </p>

                  <p class="li-time"></p>
                  <p class="event-li-data">
                    <i class="fa fa-calendar" aria-hidden="true"></i>
                    <%= event.start_time.strftime('%a, %d %b %Y %H:%M:%S') %><br>
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <%= event.location %>
                  </p>
                </div>
              </li>
              </div>
            <% end %>

            <% end %>

          </ul>
        </div>
    </div>
  </div>
</div>



    </div>
  </div>
<!-- </div> -->

app/views/events/new.html.erb
<div class="container create-wrapper" style="margin-bottom: 30px;">
  <h2 class="text-center">Create a new event</h2>
  <div class="row">
    <div class='col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3'>
      <%= simple_form_for @event do |f| %>  <!-- remote: true -->
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :title, required: true, autofocus: true %>
          <%= f.input :location, required: true, autofocus: true %>
          <%= f.input :start_time,as: :string, required: true, autofocus: true, input_html: {id: "datetimepicker1"} %>
          <%= f.input :end_time, as: :string, required: true, autofocus: true, input_html: {id: "datetimepicker2"} %>
          <%= f.input :description, required: true, autofocus: true %>
          <%= f.input :organization, required: false, autofocus: true %>
          <%= f.input :category, required: true, autofocus: true %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>


        <div class="form-actions">
          <%= f.button :submit, "Create event", class: "btn btn-primary"  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<!-- Javascript for check-in -->
<% content_for(:after_js) do %>
  <script>
  $(document).ready(function () {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          var lat = position.coords.latitude;
          var long = position.coords.longitude;

          var previous_href = $(".js-location").attr("href");
          previous_href = previous_href + "?latitude=" + lat + "&longitude=" + long;

          $(".js-location").attr("href", previous_href);
          console.log(lat);
          console.log(long);

        });
    }
  });
  </script>
<% end %>

<div class="show-wrapper">
<!-- BANNER WITH CHECK-IN BUTTON -->
  <% if @event.photo? %>
    <div class="banner-event" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.5) 50%), url('<%= cl_image_path @event.photo %>')">
  <% else %>
    <div class="banner-event" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.5) 50%), url('https://images.unsplash.com/photo-1478812954026-9c750f0e89fc?dpr=1&auto=format&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb&crop=&bg=')">
  <% end %>
      <div class="banner-event-text">
        <h1><%= @event.title %></h1>
        <% if @event.upcomming? %>
          <h3>This event is to come. At the event, you will be able to check in to enable the chat and view the other attendees</h3>
        <% elsif @event.now? %>
          <h3>This event is NOW</h3>
          <% if user_signed_in?%>
            <% attended = current_user.attendances.select { |attendance| attendance.event_id == @event.id } %>
            <% if attended.empty? %>
              <div class="btn-show">
                <%= link_to "Check in", event_attend_path(@event), method: :get, class: "navbar-wagon-item navbar-wagon-button btn js-location" %>
              </div>
            <% else %>
              <h3>You are checked in.</h3>
            <% end %>
          <% else %>
            <div class="btn-show">
              <%= link_to "Check in", event_attend_path(@event), method: :get, class: "navbar-wagon-item navbar-wagon-button btn js-location"  %>
            </div>
          <% end %>
        <% elsif @event.past? %>
          <h3>This event is no longer open for check-ins.</h3>
        <% end %>
      </div>
    </div>
  <!-- end of banner -->

  <div class="container show-box" >
    <div class="row">

        <!-- Description -->
      <div class="event-infos">
        <div class="col-md-6">
          <p><i class="fa fa-calendar icon-design" aria-hidden="true"></i> <%= l(@event.start_time, format: :long) %> </p>
          <hr>
          <p><i class="fa fa-map-marker lg icon-design" aria-hidden="true"></i> <%= @event.location %> </p>
          <hr>
          <p><i class="fa fa-briefcase icon-design" aria-hidden="true"></i> <%= @event.organization %> </p>
          <hr>
          <p><i class="fa fa-tags icon-design" aria-hidden="true"></i> <%= @event.category %> </p>
          <hr>
          <p><i class="fa fa-bolt icon-design" aria-hidden="true"></i> <%= @event.description %>

        </div>
      </div>



    <% if !@event.upcomming? %>

      <!-- List of attendances -->
      <div class="col-xs-12 col-md-6">
        <div class= "attendances-wrapper">
          <% if user_signed_in? %>
            <% attended = current_user.attendances.select { |attendance| attendance.event_id == @event.id } %>
            <% if attended.empty? == false %>
              <h2 class="text-center"> <%= pluralize @event.attendances.count, "checked-in attendant" %> </h2>

              <% @event.attendances.each do |attendance| %>
                <% user_id = attendance.user_id %>
                <% user = User.find(user_id) %>
                <div class="user-list">
                  <% avatar_url = user.picture || "https://timeforgeography.co.uk/static/img/avatar-placeholder.png" %>
                  <%= image_tag avatar_url, class: "user-list-avatar" %>
                  <div class='user-list-body'>
                    <a href="<%= user_path(user.id, :event => @event.id) %>" style="text-decoration: none; color: #333333;"><h5> <%= user.first_name + " " + user.last_name %> </h5> </a>
                    <p> <%= user.headline %> </p>
                  </div>
                  <ul class="list-inline user-list-controls">
                    <% unless user.url.nil? %>
                      <li><a href="<%= user.url %>" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                    <% end %>

                    <!-- Check if user already has a chat with this guy -->
                    <% my_chats = current_user.chatroomusers %>
                    <% unless my_chats.empty? %>
                      <% already_chatting = false %>
                      <% my_chats.each do |chat| %>
                        <% if chat.chatroom.chatroomusers.size < 2 %>
                          <% next %>
                        <% end %>

                        <% chatter_1 = chat.chatroom.chatroomusers[0].user %>
                        <% chatter_2 = chat.chatroom.chatroomusers[1].user %>
                        <% chatters = [chatter_1, chatter_2] %>
                        <% if chatters.include?(user) %>
                          <% already_chatting = true %>
                          <% @our_chatroom = chat.chatroom %>
                        <% end %>
                      <% end %>
                    <% end %>

                    <% unless already_chatting %>
                      <li><a href="<%= new_chatroom_path(with_user_id: user_id) %>"><i class="fa fa-comments"></i></a></li>
                    <% else %>
                      <li><a href="<%= chatroom_path(@our_chatroom.id) %>"><i class="fa fa-comments"></i></a></li>
                    <% end %>
                    <li><%= link_to "", event_addcontactbook_path(@event,:user_id => user_id), :class => "fa fa-address-book" %></li>
                  </ul>
                </div>
              <% end %>

            <% else %>
              <div class="hidden-list">
                <h3> <%= pluralize @event.attendances.count, "checked-in attendant" %></h3>
                <p>Head over to the event and check in to see who they are!</p>
              </div>
            <% end %>
          <% else %>
            <div class="hidden-list">
              <h3> <%= pluralize @event.attendances.count, "checked-in attendant" %></h3>
              <p>Head over to the event and check in to see who they are!</p>
            </div>
          <% end %>
          </div>
        </div>

        <!-- map -->
      <div class="wrapper-map">
          <div id="map" style="width: 100%; height: 145px;"></div>

            <% content_for(:after_js) do %>
              <%= javascript_tag do %>
                $(document).ready(function() {
                  var handler = Gmaps.build('Google');
                  handler.buildMap({ internal: { id: 'map' }, provider:{ scrollwheel: false } }, function() {
                    markers = handler.addMarkers(<%= raw @hash.to_json %>);
                    handler.bounds.extendWith(markers);
                    handler.fitMapToBounds();
                    if (markers.length == 0) {
                      handler.getMap().setZoom(2);
                    } else if (markers.length == 1) {
                      handler.getMap().setZoom(14);
                    }
                  });
                });

              <% end %>
            <% end %>
      </div>
      <!-- end map -->

      </div>
    </div>
  <% end %>
</div>



<!-- NOTE: Create banner with image, logo, slogan and randomized quotes, including:
  "You're only as strong as your network." - Barrack Obama
  "No man is an island." - Ernest Hemingway
  "My big fat network is so annoying and never helped me with anything." - No one ever
 -->

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>