config/routes.rb
Rails.application.routes.draw do

  # Chat
  mount ActionCable.server => '/cable'
  resources :chatrooms
  resources :messages

  # Contacts
  resources :contacts, except: [:new, :create, :show]
  get "contacts/search", to: "contacts#search"

  # Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Events
  resources :events, except: [:index] do
    get 'attend', to: "events#attend"
    get 'addcontactbook', to: "events#addcontactbook"
  end

  get 'events', to: "events#search", as: 'search'
  
  # Attendances
  resources :attendances, only: [:destroy] do
    collection do
      get 'dashboard', to: "attendances#dashboard"
    end
  end
 
  # LinkedIn sign in/sign up
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  # Profile page
  resources :users, only: [:show]
  
  root to: 'pages#home'
  
end

app/models/contact.rb
class Contact < ApplicationRecord
  include PgSearch
  belongs_to :user
  belongs_to :user_contact, class_name: 'User'

  pg_search_scope :global_search,
    against: [ :notes, :category ],
    associated_against: {
      user_contact: [ :first_name, :last_name, :industry ]
    }, using: {tsearch: {prefix: true, any_word: true}}

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController



  def index

    if params.has_key?(:search_value) and params[:search_value] !=""
      search = params[:search_value]
      @result = Contact.global_search(search)
    else

      @user = current_user
    end
  end

  def show
    @contact = Contact.find(params[:contact_id])
    @user = User.find(params[:id])
  end


  def edit
respond_to do |format|
  format.js {render layout: false} # Add this line to you respond_to block
end
  end

  def destroy
    @user_contact_id = params[:id]
    @contact = Contact.find_by(user_contact_id: @user_contact_id)
    @contact.destroy
    redirect_to contacts_path
  end

  def update
    @contact = Contact.find(params[:contact_id])
    @user = User.find(params[:id])
    @contact.update(contact_details)
     respond_to do |format|
          format.html { redirect_to user_path(@user) }
          format.js { @contact }  # <-- will render `app/views/reviews/create.js.erb`
        end
  end



  private

  def contact_details
    params.require(:contact).permit(:notes, :category)
  end

end

app/views/contacts/_edit.html.erb
    <div class="form-inputs">
     <%= simple_form_for (@contact), remote: true,  :url => url_for(:action => 'update', :controller => 'contacts', contact_id: @contact.id), :method => 'patch' do |f|  %>
     <%= f.text_area :notes, autofocus: true %>
     <%= f.input :category, autofocus: true %>
     <%= f.submit %>
     <% end %>
   </div>

app/views/contacts/destroy.html.erb
<h1>Contacts#destroy</h1>
<p>Find me in app/views/contacts/destroy.html.erb</p>

app/views/contacts/index.html.erb
<!-- <div class="contact-search-wrapper">
  <%#= form_tag('/contacts', method: 'get',  class:'navbar-wagon-search' ) do  %>
    <%#= text_field_tag :search_value, params[:search_value], placeholder: 'Enter search term...' , class: "navbar-wagon-search-input" %>
    <%#= submit_tag 'search', class: 'btn btn-primary search-btn' %>
  <%# end %>
</div> -->

<div class="contacts-wrapper">
  <div class="container-fluid search-wrapper">
    <div class="row">
      <div class="col-xs-12">
        <h4 class="text-center">Contact book</h4>
        <%= form_tag('/contacts', method: 'get',  class:'navbar-wagon-search ', role: "search" ) do  %>
          <%= text_field_tag :search_value, params[:search_value], placeholder: 'Enter search term...' , class: "navbar-wagon-search-input" %>
          <%= button_tag '', class: 'btn btn-primary search-btn' do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>



  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <!-- if no params or you can't match, display a whole list -->
        <%if params[:search_value] == nil or params[:search_value] == ""  %>

        <% current_user.contacts.each do |contact| %>
          <% user_id = contact.user_contact_id %>
          <% user = User.find(user_id) %>

          <div class="user-list">
            <% avatar_url = user.picture || "https://timeforgeography.co.uk/static/img/avatar-placeholder.png" %>
            <%= image_tag avatar_url, class: "user-list-avatar" %>
            <div class='user-list-body'>

              <a href="<%= user_path(user.id) %>" style="text-decoration: none; color: #333333;"> <h5> <%= user.first_name %> <%= user.last_name  %> </h5> </a>
              <p> <%= user.headline %> </p>
            </div>
            <ul class="list-inline user-list-controls"> <!-- hidden-sm hidden-xs -->
              <% unless user.url.nil? %>
              <li><a href="<%= user.url %>" target="_blank"><i class="fa fa-linkedin"></i></a></li>
              <% end %>
              <li><a href="#"><i class="fa fa-comments"></i></a></li>

              <li><%= link_to "", contact_path(user_id), method: :delete,class: "fa fa-trash" %></li>
            </ul>
          </div>
        <% end %>

        <%elsif params[:search_value] != nil  %>

        <% @result.each do |contact| %>
          <% user_id = contact.user_contact_id %>
          <% user = User.find(user_id) %>



          <div class="user-list">
            <% avatar_url = user.picture || "https://timeforgeography.co.uk/static/img/avatar-placeholder.png" %>
            <%= image_tag avatar_url, class: "user-list-avatar" %>
            <div class='user-list-body'>

              <a href="<%= user_path(user.id) %>" style="text-decoration: none; color: #333333;"> <h5> <%= user.first_name %> <%= user.last_name  %> </h5> </a>
              <p> <%= user.headline %> </p>
            </div>
            <ul class="list-inline user-list-controls"> <!-- hidden-sm hidden-xs -->
              <% unless user.url.nil? %>
              <li><a href="<%= user.url %>" target="_blank"><i class="fa fa-linkedin"></i></a></li>
              <% end %>
              <li><a href="#"><i class="fa fa-comments"></i></a></li>

              <li><%= link_to "", contact_path(user_id), method: :delete,class: "fa fa-trash" %></li>
            </ul>
          </div>
        <% end %>

        <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Find me in app/views/contacts/show.html.erb</p>

app/views/contacts/update.js.erb
$(".contact-category").text("<%= @contact.category %>");

$(".contact-notes").text("<%= @contact.notes %>");