config/routes.rb
Rails.application.routes.draw do

  # Chat
  mount ActionCable.server => '/cable'
  resources :chatrooms
  resources :messages

  # Contacts
  resources :contacts, except: [:new, :create, :show]
  get "contacts/search", to: "contacts#search"

  # Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Events
  resources :events, except: [:index] do
    get 'attend', to: "events#attend"
    get 'addcontactbook', to: "events#addcontactbook"
  end

  get 'events', to: "events#search", as: 'search'
  
  # Attendances
  resources :attendances, only: [:destroy] do
    collection do
      get 'dashboard', to: "attendances#dashboard"
    end
  end
 
  # LinkedIn sign in/sign up
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  # Profile page
  resources :users, only: [:show]
  
  root to: 'pages#home'
  
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  #  before_action :require_login, only: [:dashboard]
   #add before_action event.save control (user_id: @user.id, event_id: @event.id) doesn't exist

  def dashboard
    @organized_events = current_user.events.order(start_time: :asc).select{|event| event.start_time > (Time.now - (2*7*24*60*60)) }
    @events = current_user.events_to_attend.order(start_time: :asc).select{|event| event.start_time > (Time.now - (2*7*24*60*60)) }
    @user = current_user
  end


  def destroy
    # @user = current_user
    # @events = current_user.events_to_attend.order(start_time: :asc).select{|event| event.start_time > Time.now }
    # @events.each do |event|
    #   @attendance = current_user.attendances.where(event: event).first
    #   unless @attendance.nil?
    #   @attendance.destroy
    #
    #   end
    # end
    @attendance = Attendance.find(params[:id])
    @attendance.destroy
    redirect_to dashboard_attendances_path
  end
end

app/views/attendances/dashboard.html.erb
<div class="container-fluid dashboard text-center">
  <div class="row">
    <div class="col-xs-12 dashboard-page">
      <%#= link_to "", new_event_path, class: "fa fa-plus-square-o fa-2x"%>

      <div class="profile-header-wrapper">
        <div class="profile-header-container text-center">
          <div class="tabs">
            <a class="tab active" data-target="#attending">
              <!-- <h3>Attending</h3> -->
              <i class="material-icons">event</i> Your events
            </a>
            <a class="tab" data-target="#created">
              <i class="material-icons">note_add</i>Created events
            </a>
          </div>
        </div>
      </div>


      <div class="text-center dashboard-body"> <!-- .container -->
        <div class="tab-content" id="attending">

          <% if current_user.events_to_attend.empty? %>
            <p class="blank-dashboard text-center">It seems like you're not attending any events yet.</p>
          <% else %>
            <% @events.each do |event| %>
              <!-- <h5 class="event-title"><%= link_to event.title, event_path(event) %></h5> -->

              <% if ((Time.now) > (event.start_time - 2.hours - 15.minutes)) && (Time.now < (event.start_time - 2.hours) ) %>
                  <p class="event-status">Event is about to start, make sure to check in!</p>
              <% elsif ((event.start_time - 2.hours) <= Time.now) && ((event.end_time - 2.hours) >= Time.now) %>
                    <p class="event-status">This event is now live!</p>
              <% end %>
              <% @attendance = current_user.attendances.where(event: event).first %>
              <p class="event-time">&#8226; <%= event.start_time.strftime('%a, %d %b %H:%M') %> &#8226;</p>

              <p class="event-title"><%= link_to event.title, event_path(event) %></p>

              <p class="unbook" style="font-weight: lighter"><%= link_to "Unbook this event", attendance_path(@attendance), method: :delete, data: {confirm: "are you sure ?"} %></p>
            <% end %>
          <% end %>
        </div>

        <div class="tab-content hidden" id="created">
          <% if current_user.events.empty? %>
            <p class="blank-dashboard text-center">There's nothing here :( Create your first event!</p>
          <% else %>
            <% @organized_events.each do |event| %>
              <p><%#= event.start_time%></p>


              <!-- <h5 class="event-title"> <%= link_to event.title, event_path(event) %> </h5> -->

              <% if ((Time.now) > (event.start_time - 2.hours - 15.minutes)) && (Time.now < (event.start_time - 2.hours) ) %>
                <p class="event-status">Event is about to start!</p>
              <% elsif ((event.start_time - 2.hours) <= Time.now) && ((event.end_time - 2.hours) >= Time.now) %>
                <p class="event-status">This event is now live!</p>
              <% end %>

              <p class="event-time">&#8226; <%= event.start_time.strftime('%a, %d %b %H:%M') %> &#8226;</p>
              <p class="event-title"> <%= link_to event.title, event_path(event) %> </p>
              <p class="unbook" style="font-weight: lighter"> <%= link_to "Edit event", edit_event_path(event) %> </p>
            <% end %>
          <% end %>
        </div>
      </div>


    </div>
  </div>
</div>
<!-- linkedin photo here -->